all:
  ice_libs:
    routing:
      secret: 'yWJ2wUvHwZDnub7MtZLh2Zknd8TFXQGa'

    emails:
      sender: 'no-reply@icepique.com'
      notify: 'developers@icepique.com'

    kint:
      enabled: false
      path_display_callback: 'Kint::_kintLine'
      max_str_length: 60
      max_levels: 5
      skin: kint.css
